//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FakTest.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FakTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Adres.
        /// </summary>
        public static string DKW_Adres {
            get {
                return ResourceManager.GetString("DKW_Adres", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu iddd.
        /// </summary>
        public static string DKW_DataGrid_1 {
            get {
                return ResourceManager.GetString("DKW_DataGrid_1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Id.
        /// </summary>
        public static string DKW_DG_1 {
            get {
                return ResourceManager.GetString("DKW_DG_1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa.
        /// </summary>
        public static string DKW_DG_2 {
            get {
                return ResourceManager.GetString("DKW_DG_2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu NIP.
        /// </summary>
        public static string DKW_DG_3 {
            get {
                return ResourceManager.GetString("DKW_DG_3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Telefon.
        /// </summary>
        public static string DKW_DG_4 {
            get {
                return ResourceManager.GetString("DKW_DG_4", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kod.
        /// </summary>
        public static string DKW_DG_5 {
            get {
                return ResourceManager.GetString("DKW_DG_5", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Adres.
        /// </summary>
        public static string DKW_DG_6 {
            get {
                return ResourceManager.GetString("DKW_DG_6", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj nowego klienta.
        /// </summary>
        public static string DKW_Dodaj {
            get {
                return ResourceManager.GetString("DKW_Dodaj", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kod.
        /// </summary>
        public static string DKW_Kod {
            get {
                return ResourceManager.GetString("DKW_Kod", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa.
        /// </summary>
        public static string DKW_Nazwa {
            get {
                return ResourceManager.GetString("DKW_Nazwa", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu NIP.
        /// </summary>
        public static string DKW_NIP {
            get {
                return ResourceManager.GetString("DKW_NIP", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Telefon.
        /// </summary>
        public static string DKW_Telefon {
            get {
                return ResourceManager.GetString("DKW_Telefon", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cena.
        /// </summary>
        public static string DPW_Cena {
            get {
                return ResourceManager.GetString("DPW_Cena", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Id.
        /// </summary>
        public static string DPW_DG_1 {
            get {
                return ResourceManager.GetString("DPW_DG_1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa.
        /// </summary>
        public static string DPW_DG_2 {
            get {
                return ResourceManager.GetString("DPW_DG_2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Typ.
        /// </summary>
        public static string DPW_DG_3 {
            get {
                return ResourceManager.GetString("DPW_DG_3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Netto.
        /// </summary>
        public static string DPW_DG_4 {
            get {
                return ResourceManager.GetString("DPW_DG_4", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu %.
        /// </summary>
        public static string DPW_DG_5 {
            get {
                return ResourceManager.GetString("DPW_DG_5", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Vat.
        /// </summary>
        public static string DPW_DG_6 {
            get {
                return ResourceManager.GetString("DPW_DG_6", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brutto.
        /// </summary>
        public static string DPW_DG_7 {
            get {
                return ResourceManager.GetString("DPW_DG_7", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj nowy produkt.
        /// </summary>
        public static string DPW_Dodaj {
            get {
                return ResourceManager.GetString("DPW_Dodaj", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa.
        /// </summary>
        public static string DPW_Nazwa {
            get {
                return ResourceManager.GetString("DPW_Nazwa", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Stawka VAT.
        /// </summary>
        public static string DPW_Vat {
            get {
                return ResourceManager.GetString("DPW_Vat", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wczytaj.
        /// </summary>
        public static string MW_ButtonLoad {
            get {
                return ResourceManager.GetString("MW_ButtonLoad", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Obsługa.
        /// </summary>
        public static string MW_ButtonOptions {
            get {
                return ResourceManager.GetString("MW_ButtonOptions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisz.
        /// </summary>
        public static string MW_ButtonSave {
            get {
                return ResourceManager.GetString("MW_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sprzedaż.
        /// </summary>
        public static string MW_ButtonSell {
            get {
                return ResourceManager.GetString("MW_ButtonSell", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Okno główne.
        /// </summary>
        public static string MW_MainWindowHeader {
            get {
                return ResourceManager.GetString("MW_MainWindowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Obsługa bazy.
        /// </summary>
        public static string OW_BaseHeader {
            get {
                return ResourceManager.GetString("OW_BaseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj nowy produkt.
        /// </summary>
        public static string OW_ButtonAddNewProduct {
            get {
                return ResourceManager.GetString("OW_ButtonAddNewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Generuj JPK.
        /// </summary>
        public static string OW_ButtonGenerateJPK {
            get {
                return ResourceManager.GetString("OW_ButtonGenerateJPK", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Generuj raport sprzedaży.
        /// </summary>
        public static string OW_ButtonGenerateRaport {
            get {
                return ResourceManager.GetString("OW_ButtonGenerateRaport", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nowa kategoria.
        /// </summary>
        public static string OW_ButtonNewCat {
            get {
                return ResourceManager.GetString("OW_ButtonNewCat", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nowy stały klient.
        /// </summary>
        public static string OW_ButtonNewClient {
            get {
                return ResourceManager.GetString("OW_ButtonNewClient", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nowy produkt.
        /// </summary>
        public static string OW_ButtonNewProduct {
            get {
                return ResourceManager.GetString("OW_ButtonNewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Finanse.
        /// </summary>
        public static string OW_FinanceHeader {
            get {
                return ResourceManager.GetString("OW_FinanceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Okno Obsługi.
        /// </summary>
        public static string OW_OptionsWindowHeader {
            get {
                return ResourceManager.GetString("OW_OptionsWindowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Asortyment.
        /// </summary>
        public static string SW_AsortymentHeader {
            get {
                return ResourceManager.GetString("SW_AsortymentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &gt;.
        /// </summary>
        public static string SW_ButtonAddProd {
            get {
                return ResourceManager.GetString("SW_ButtonAddProd", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Finalizuj.
        /// </summary>
        public static string SW_ButtonFinalize {
            get {
                return ResourceManager.GetString("SW_ButtonFinalize", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;.
        /// </summary>
        public static string SW_ButtonRemoveProd {
            get {
                return ResourceManager.GetString("SW_ButtonRemoveProd", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Szukaj.
        /// </summary>
        public static string SW_ButtonSearch {
            get {
                return ResourceManager.GetString("SW_ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Koszyk.
        /// </summary>
        public static string SW_KoszykHeader {
            get {
                return ResourceManager.GetString("SW_KoszykHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Faktura Vat.
        /// </summary>
        public static string SW_Option1 {
            get {
                return ResourceManager.GetString("SW_Option1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Paragon.
        /// </summary>
        public static string SW_Option2 {
            get {
                return ResourceManager.GetString("SW_Option2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Odroczony termin płatności.
        /// </summary>
        public static string SW_Option3 {
            get {
                return ResourceManager.GetString("SW_Option3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa Produktu.
        /// </summary>
        public static string SW_ProductNameHeader {
            get {
                return ResourceManager.GetString("SW_ProductNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Typ produktu.
        /// </summary>
        public static string SW_ProductTypeHeader {
            get {
                return ResourceManager.GetString("SW_ProductTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wyszukiwanie: nazwa Produktu lub id.
        /// </summary>
        public static string SW_SearchHeader {
            get {
                return ResourceManager.GetString("SW_SearchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Okno sprzedaży.
        /// </summary>
        public static string SW_SellWindowHeader {
            get {
                return ResourceManager.GetString("SW_SellWindowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Powrót.
        /// </summary>
        public static string U_ButtonBack {
            get {
                return ResourceManager.GetString("U_ButtonBack", resourceCulture);
            }
        }
    }
}
