//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FakTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FakTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string DKW_Adres {
            get {
                return ResourceManager.GetString("DKW_Adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontynuuj transakcje.
        /// </summary>
        public static string DKW_ButtonContinueTransaction {
            get {
                return ResourceManager.GetString("DKW_ButtonContinueTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iddd.
        /// </summary>
        public static string DKW_DataGrid_1 {
            get {
                return ResourceManager.GetString("DKW_DataGrid_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string DKW_DG_1 {
            get {
                return ResourceManager.GetString("DKW_DG_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        public static string DKW_DG_2 {
            get {
                return ResourceManager.GetString("DKW_DG_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP.
        /// </summary>
        public static string DKW_DG_3 {
            get {
                return ResourceManager.GetString("DKW_DG_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string DKW_DG_4 {
            get {
                return ResourceManager.GetString("DKW_DG_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod.
        /// </summary>
        public static string DKW_DG_5 {
            get {
                return ResourceManager.GetString("DKW_DG_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string DKW_DG_6 {
            get {
                return ResourceManager.GetString("DKW_DG_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj nowego klienta.
        /// </summary>
        public static string DKW_Dodaj {
            get {
                return ResourceManager.GetString("DKW_Dodaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod.
        /// </summary>
        public static string DKW_Kod {
            get {
                return ResourceManager.GetString("DKW_Kod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        public static string DKW_Nazwa {
            get {
                return ResourceManager.GetString("DKW_Nazwa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP.
        /// </summary>
        public static string DKW_NIP {
            get {
                return ResourceManager.GetString("DKW_NIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string DKW_Telefon {
            get {
                return ResourceManager.GetString("DKW_Telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena.
        /// </summary>
        public static string DPW_Cena {
            get {
                return ResourceManager.GetString("DPW_Cena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string DPW_DG_1 {
            get {
                return ResourceManager.GetString("DPW_DG_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        public static string DPW_DG_2 {
            get {
                return ResourceManager.GetString("DPW_DG_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ.
        /// </summary>
        public static string DPW_DG_3 {
            get {
                return ResourceManager.GetString("DPW_DG_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netto.
        /// </summary>
        public static string DPW_DG_4 {
            get {
                return ResourceManager.GetString("DPW_DG_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string DPW_DG_5 {
            get {
                return ResourceManager.GetString("DPW_DG_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat.
        /// </summary>
        public static string DPW_DG_6 {
            get {
                return ResourceManager.GetString("DPW_DG_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brutto.
        /// </summary>
        public static string DPW_DG_7 {
            get {
                return ResourceManager.GetString("DPW_DG_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj nowy produkt.
        /// </summary>
        public static string DPW_Dodaj {
            get {
                return ResourceManager.GetString("DPW_Dodaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        public static string DPW_Nazwa {
            get {
                return ResourceManager.GetString("DPW_Nazwa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stawka VAT.
        /// </summary>
        public static string DPW_Vat {
            get {
                return ResourceManager.GetString("DPW_Vat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO {
            get {
                object obj = ResourceManager.GetObject("LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wczytaj.
        /// </summary>
        public static string MW_ButtonLoad {
            get {
                return ResourceManager.GetString("MW_ButtonLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsługa.
        /// </summary>
        public static string MW_ButtonOptions {
            get {
                return ResourceManager.GetString("MW_ButtonOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string MW_ButtonSave {
            get {
                return ResourceManager.GetString("MW_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprzedaż.
        /// </summary>
        public static string MW_ButtonSell {
            get {
                return ResourceManager.GetString("MW_ButtonSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string MW_DG_1 {
            get {
                return ResourceManager.GetString("MW_DG_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data transakcji.
        /// </summary>
        public static string MW_DG_2 {
            get {
                return ResourceManager.GetString("MW_DG_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okno główne.
        /// </summary>
        public static string MW_MainWindowHeader {
            get {
                return ResourceManager.GetString("MW_MainWindowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsługa bazy.
        /// </summary>
        public static string OW_BaseHeader {
            get {
                return ResourceManager.GetString("OW_BaseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj nowy produkt.
        /// </summary>
        public static string OW_ButtonAddNewProduct {
            get {
                return ResourceManager.GetString("OW_ButtonAddNewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generuj JPK.
        /// </summary>
        public static string OW_ButtonGenerateJPK {
            get {
                return ResourceManager.GetString("OW_ButtonGenerateJPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generuj raport sprzedaży.
        /// </summary>
        public static string OW_ButtonGenerateRaport {
            get {
                return ResourceManager.GetString("OW_ButtonGenerateRaport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy stały klient.
        /// </summary>
        public static string OW_ButtonNewClient {
            get {
                return ResourceManager.GetString("OW_ButtonNewClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy produkt.
        /// </summary>
        public static string OW_ButtonNewProduct {
            get {
                return ResourceManager.GetString("OW_ButtonNewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż transakcje.
        /// </summary>
        public static string OW_ButtonShowTransactions {
            get {
                return ResourceManager.GetString("OW_ButtonShowTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finanse.
        /// </summary>
        public static string OW_FinanceHeader {
            get {
                return ResourceManager.GetString("OW_FinanceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okno Obsługi.
        /// </summary>
        public static string OW_OptionsWindowHeader {
            get {
                return ResourceManager.GetString("OW_OptionsWindowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asortyment.
        /// </summary>
        public static string SW_AsortymentHeader {
            get {
                return ResourceManager.GetString("SW_AsortymentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        public static string SW_ButtonAddProd {
            get {
                return ResourceManager.GetString("SW_ButtonAddProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizuj.
        /// </summary>
        public static string SW_ButtonFinalize {
            get {
                return ResourceManager.GetString("SW_ButtonFinalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        public static string SW_ButtonRemoveProd {
            get {
                return ResourceManager.GetString("SW_ButtonRemoveProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukaj.
        /// </summary>
        public static string SW_ButtonSearch {
            get {
                return ResourceManager.GetString("SW_ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koszyk.
        /// </summary>
        public static string SW_KoszykHeader {
            get {
                return ResourceManager.GetString("SW_KoszykHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faktura Vat.
        /// </summary>
        public static string SW_Option1 {
            get {
                return ResourceManager.GetString("SW_Option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragon.
        /// </summary>
        public static string SW_Option2 {
            get {
                return ResourceManager.GetString("SW_Option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odroczony termin płatności.
        /// </summary>
        public static string SW_Option3 {
            get {
                return ResourceManager.GetString("SW_Option3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa Produktu.
        /// </summary>
        public static string SW_ProductNameHeader {
            get {
                return ResourceManager.GetString("SW_ProductNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ produktu.
        /// </summary>
        public static string SW_ProductTypeHeader {
            get {
                return ResourceManager.GetString("SW_ProductTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz nazwe produktu.
        /// </summary>
        public static string SW_SearchHeader {
            get {
                return ResourceManager.GetString("SW_SearchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okno sprzedaży.
        /// </summary>
        public static string SW_SellWindowHeader {
            get {
                return ResourceManager.GetString("SW_SellWindowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string TW_DG_1 {
            get {
                return ResourceManager.GetString("TW_DG_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP.
        /// </summary>
        public static string TW_DG_2 {
            get {
                return ResourceManager.GetString("TW_DG_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string TW_DG_3 {
            get {
                return ResourceManager.GetString("TW_DG_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr fak.
        /// </summary>
        public static string TW_DG_4 {
            get {
                return ResourceManager.GetString("TW_DG_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id produktów.
        /// </summary>
        public static string TW_DG_5 {
            get {
                return ResourceManager.GetString("TW_DG_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string TW_DG_6 {
            get {
                return ResourceManager.GetString("TW_DG_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netto.
        /// </summary>
        public static string TW_DG_7 {
            get {
                return ResourceManager.GetString("TW_DG_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat.
        /// </summary>
        public static string TW_DG_8 {
            get {
                return ResourceManager.GetString("TW_DG_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powrót.
        /// </summary>
        public static string U_ButtonBack {
            get {
                return ResourceManager.GetString("U_ButtonBack", resourceCulture);
            }
        }
    }
}
